language: objective-c
osx_image: xcode10
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator12.0
#  - TVOS_SDK=appletvsimulator12.0
script:
  - xcodebuild -showsdks
  - xcodebuild -project Twinkle/Twinkle.xcodeproj -scheme 'Debug - iOS' -sdk $IOS_SDK build analyze
#  - xcodebuild -project Twinkle/Twinkle.xcodeproj -scheme 'Debug - tvOS' -sdk $TVOS_SDK build analyze
