language: objective-c
osx_image: xcode9.4
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator11.4
#  - TVOS_SDK=appletvsimulator11.4
script:
  - xcodebuild -showsdks
  - xcodebuild -project Twinkle/Twinkle.xcodeproj -scheme 'Debug - iOS' -sdk $IOS_SDK build analyze
#  - xcodebuild -project Twinkle/Twinkle.xcodeproj -scheme 'Debug - tvOS' -sdk $TVOS_SDK build analyze
